
import Project.connectionProvider;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javi
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        isbn_Input = new javax.swing.JTextField();
        studentIDInput = new javax.swing.JTextField();
        issueDateChooser = new com.toedter.calendar.JDateChooser();
        dueDateChooser = new com.toedter.calendar.JDateChooser();
        issueBook = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(980, 195));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 27, 52));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ISBN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 70, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("StudentID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 90, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issue Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 100, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Due Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, 30));

        isbn_Input.setBackground(new java.awt.Color(255, 255, 255));
        isbn_Input.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(isbn_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 240, 30));

        studentIDInput.setBackground(new java.awt.Color(255, 255, 255));
        studentIDInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(studentIDInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 240, 30));
        jPanel1.add(issueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 240, 30));
        jPanel1.add(dueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 240, 30));

        issueBook.setBackground(new java.awt.Color(48, 50, 78));
        issueBook.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        issueBook.setForeground(new java.awt.Color(255, 255, 255));
        issueBook.setText("Issue");
        issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookActionPerformed(evt);
            }
        });
        jPanel1.add(issueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 130, 40));

        jPanel3.setBackground(new java.awt.Color(48, 50, 78));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Issue Book");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookActionPerformed
        // issue Book
        
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        
        String isbn = isbn_Input.getText();
        String studentID = studentIDInput.getText();
        String issueDate = dFormat.format(issueDateChooser.getDate());
        String dueDate = dFormat.format(dueDateChooser.getDate());
        String returnBook = "No";
        
        try {
            Connection con = connectionProvider.getCon();
           
            Statement st = con.createStatement();
            
            // Check if ISBN(Book) is in the catalogue
            ResultSet rs = st.executeQuery("SELECT * FROM book WHERE isbn='"+isbn+"'");
            
            if(rs.next()) {
                // Check if studentID(studentaccount) exists
                ResultSet rs1 = st.executeQuery("SELECT * FROM student WHERE studentID = '"+studentID+"'");
                
                if(rs1.next()) {
                    // Update databe table if both Book and Student account exists

                    st.executeUpdate("INSERT INTO issue VALUES('"+isbn+"' ,'"+studentID+"','"+issueDate+"','"+dueDate+"','"+returnBook+"')");   
                    //CREATE TABLE issue (isbn varchar(15),studentID varchar(20),issueDate varchar(20), dueDate varchar(100),returnBook varchar(20));
                    JOptionPane.showMessageDialog(null, "Book issue was successful");
                    
                    // close current and open new Issue Window
                    setVisible(false);
                    new IssueBook().setVisible(true);
                   
                    
                } else {
                    JOptionPane.showMessageDialog(null,"Incorrect StudentID");
                }
                
           
            } else {
                JOptionPane.showMessageDialog(null,  "Incorrect ISBN");
            } 
        }
        // 
        catch( Exception e){
            
            JOptionPane.showMessageDialog(null,  "Connection error");
        }
              
        
    }//GEN-LAST:event_issueBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dueDateChooser;
    private javax.swing.JTextField isbn_Input;
    private javax.swing.JButton issueBook;
    private com.toedter.calendar.JDateChooser issueDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField studentIDInput;
    // End of variables declaration//GEN-END:variables

    JPanel getJPanel2() {
        return jPanel1;
    }
}
