/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Project.connectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *  @author Mohamad
 * matriculation number: 1310757
 * @author Yousef
 * matriculation number: 1310760
 */
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form newStudent
     */
    public NewStudent() {
        initComponents();
      
    }
    ///////////////////////////
     private Home home;
    public NewStudent(Home home) {
        this.home = home;
    }
    ///////////////////////////
     JPanel getJPanel2() {
        return jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        studentIdInput = new javax.swing.JTextField();
        studentNameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        studentSurnameInput = new javax.swing.JTextField();
        courseName_ = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        branchName_ = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        addStudent = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(980, 195));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1520, -190, -1, -1));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(24, 27, 52));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentIdInput.setBackground(new java.awt.Color(255, 255, 255));
        studentIdInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        studentIdInput.setForeground(new java.awt.Color(0, 0, 0));
        studentIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdInputActionPerformed(evt);
            }
        });
        jPanel1.add(studentIdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 250, 30));

        studentNameInput.setBackground(new java.awt.Color(255, 255, 255));
        studentNameInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        studentNameInput.setForeground(new java.awt.Color(0, 0, 0));
        studentNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameInputActionPerformed(evt);
            }
        });
        jPanel1.add(studentNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 250, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, 30));

        studentSurnameInput.setBackground(new java.awt.Color(255, 255, 255));
        studentSurnameInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        studentSurnameInput.setForeground(new java.awt.Color(0, 0, 0));
        studentSurnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSurnameInputActionPerformed(evt);
            }
        });
        jPanel1.add(studentSurnameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 250, 30));

        courseName_.setBackground(new java.awt.Color(102, 102, 102));
        courseName_.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        courseName_.setForeground(new java.awt.Color(255, 255, 255));
        courseName_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech", "M.Tech" }));
        jPanel1.add(courseName_, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 250, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Surname");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, 30));

        branchName_.setBackground(new java.awt.Color(102, 102, 102));
        branchName_.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        branchName_.setForeground(new java.awt.Color(255, 255, 255));
        branchName_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELECTRICAL", "IT", "MECHANICAL", "MECHATRONICS" }));
        branchName_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchName_ActionPerformed(evt);
            }
        });
        jPanel1.add(branchName_, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 250, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Branch Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, 30));

        addStudent.setBackground(new java.awt.Color(48, 50, 78));
        addStudent.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addStudent.setForeground(new java.awt.Color(255, 255, 255));
        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_save_25px_1.png"))); // NOI18N
        addStudent.setText("Save");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        jPanel1.add(addStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 140, 40));

        jPanel3.setBackground(new java.awt.Color(48, 50, 78));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("New Student");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // save button in NewStudent
        String studentID=studentIdInput.getText();
        String name=studentNameInput.getText();
        String lastName=studentSurnameInput.getText();
        String courseName=(String)courseName_.getSelectedItem();
        String branchName=(String)branchName_.getSelectedItem();
        
        try {
            Connection con=connectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into student values('"+studentID+"','"+name+"','"+lastName+"','"+courseName+"','"+branchName+"')");
            //CREATE TABLE student (studentID varchar(15),name varchar(20),lastName varchar(20), courseName varchar(100),branchName varchar(20));
            JOptionPane.showMessageDialog(null,"Successfully updated");
            setVisible(false);
            new NewStudent().setVisible(true);
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Student id allready exist");
            setVisible(false);
            new NewStudent().setVisible(true);
        }
        
    }//GEN-LAST:event_addStudentActionPerformed

    private void studentIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdInputActionPerformed

    
    private void studentSurnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSurnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentSurnameInputActionPerformed

    private void studentNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameInputActionPerformed

    private void branchName_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchName_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchName_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JComboBox<String> branchName_;
    private javax.swing.JComboBox<String> courseName_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField studentIdInput;
    private javax.swing.JTextField studentNameInput;
    private javax.swing.JTextField studentSurnameInput;
    // End of variables declaration//GEN-END:variables

   

   
}
